name: rl-hft
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.21.0
  - pandas>=1.3.0
  - pytorch>=1.9.0
  - gym>=0.21.0
  - stable-baselines3>=1.5.0
  - tqdm>=4.62.0
  - pyyaml>=5.4.0
  - scikit-learn>=0.24.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - pip
  - pip:
    - gymnasium
    - shimmy 