name: rl-hft
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - psutil
  - pyyaml
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - stable-baselines3=2.3.2
  - gymnasium>=0.28.1,<0.30  # SB3와 호환되는 범위
  - pip:
      - tensorboard
      - shimmy<=0.2.1  # gymnasium <1.0과 호환되도록
