name: rl-hft
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pandas
  - matplotlib
  - gymnasium
  - stable-baselines3
  - pip
  - pip:
    - wandb
    - tensorboard 